apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/router.ex
defmodule PhoenixLiveViewStarterAppWeb.Router do
  use PhoenixLiveViewStarterAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixLiveViewStarterAppWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/page-live", PageLiveController, :index

    resources "/things", ThingController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixLiveViewStarterAppWeb do
  #   pipe_through :api
  # end
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/controllers/page_controller.ex
defmodule PhoenixLiveViewStarterAppWeb.PageController do
  use PhoenixLiveViewStarterAppWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/controllers/page_live_controller.ex
defmodule PhoenixLiveViewStarterAppWeb.PageLiveController do
  use PhoenixLiveViewStarterAppWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/controllers/thing_controller.ex
defmodule PhoenixLiveViewStarterAppWeb.ThingController do
  use PhoenixLiveViewStarterAppWeb, :controller

  alias PhoenixLiveViewStarterApp.Thingamabobbers
  alias PhoenixLiveViewStarterApp.Thingamabobbers.Thing

  def index(conn, _params) do
    things = Thingamabobbers.list_things()
    render(conn, "index.html", things: things)
  end

  def new(conn, _params) do
    changeset = Thingamabobbers.change_thing(%Thing{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"thing" => thing_params}) do
    case Thingamabobbers.create_thing(thing_params) do
      {:ok, thing} ->
        conn
        |> put_flash(:info, "Thing created successfully.")
        |> redirect(to: Routes.thing_path(conn, :show, thing))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    thing = Thingamabobbers.get_thing!(id)
    render(conn, "show.html", thing: thing)
  end

  def edit(conn, %{"id" => id}) do
    thing = Thingamabobbers.get_thing!(id)
    changeset = Thingamabobbers.change_thing(thing)
    render(conn, "edit.html", thing: thing, changeset: changeset)
  end

  def update(conn, %{"id" => id, "thing" => thing_params}) do
    thing = Thingamabobbers.get_thing!(id)

    case Thingamabobbers.update_thing(thing, thing_params) do
      {:ok, thing} ->
        conn
        |> put_flash(:info, "Thing updated successfully.")
        |> redirect(to: Routes.thing_path(conn, :show, thing))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", thing: thing, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    thing = Thingamabobbers.get_thing!(id)
    {:ok, _thing} = Thingamabobbers.delete_thing(thing)

    conn
    |> put_flash(:info, "Thing deleted successfully.")
    |> redirect(to: Routes.thing_path(conn, :index))
  end
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/live/thingamabobber_live.ex
defmodule PhoenixLiveViewStarterAppWeb.ThingamabobberLive do
  use Phoenix.LiveView

  def render(assigns) do
    PhoenixLiveViewStarterAppWeb.ThingamabobberLiveView.render("thingamabobber.html", assigns)
  end

  def mount(_session, socket) do
    {:ok, assign(socket, thing: "1")}
  end

  def handle_event("thingamabobber", _value, socket) do
    new_thing =
      case socket.assigns.thing do
        "1" -> "2"
        "2" -> "1"
      end

    {:noreply, assign(socket, thing: new_thing)}
  end
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/views/error_view.ex
defmodule PhoenixLiveViewStarterAppWeb.ErrorView do
  use PhoenixLiveViewStarterAppWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  def render("404.html", _assigns) do
    render("404_page.html", %{})
  end

  def render("500.html", _assigns) do
    render("500_page.html", %{})
  end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/views/layout_view.ex
defmodule PhoenixLiveViewStarterAppWeb.LayoutView do
  use PhoenixLiveViewStarterAppWeb, :view
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/views/page_live_view.ex
defmodule PhoenixLiveViewStarterAppWeb.PageLiveView do
  use PhoenixLiveViewStarterAppWeb, :view
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/views/page_view.ex
defmodule PhoenixLiveViewStarterAppWeb.PageView do
  use PhoenixLiveViewStarterAppWeb, :view
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/views/thing_view.ex
defmodule PhoenixLiveViewStarterAppWeb.ThingView do
  use PhoenixLiveViewStarterAppWeb, :view
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/views/thingamabobber_live_view.ex
defmodule PhoenixLiveViewStarterAppWeb.ThingamabobberLiveView do
  use PhoenixLiveViewStarterAppWeb, :view
end

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>Phoenix Live View Starter App</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
</head>

<body>
    <%= render @view_module, @view_template, assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/page/index.html.eex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_live_path(@conn, :index) %>">Live View</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.thing_path(@conn, :index) %>">Things</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<main class="main" role="main">
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-4">
                <i class="fas fa-code mr-3"></i>
                Hello, Phoenix Live View Starter App!
                <i class="fas fa-code ml-3"></i>
            </h1>
        </div>
    </div>
</main>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/page_live/index.html.eex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Live View <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.thing_path(@conn, :index) %>">Things</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<main class="main" role="main">
    <div class="jumbotron">
        <div class="container text-center">
            <%= Phoenix.LiveView.live_render(@conn, PhoenixLiveViewStarterAppWeb.ThingamabobberLive, session: %{}) %>
        </div>
    </div>
</main>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/page_live/index.html.leex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<%= @page_index_path %>">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Live View <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= @thing_index_path %>">Things</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<main class="main" role="main">
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-4">Thing <%= @thing %></h1>
            <button type="button" class="btn btn-primary" phx-click="thingamabobber">Thingamabobber</button>
        </div>
    </div>
</main>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/thing/edit.html.eex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_live_path(@conn, :index) %>">Live View</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Things <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<h1>Edit Thing</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.thing_path(@conn, :update, @thing)) %>

<span><%= link "Back", to: Routes.thing_path(@conn, :index) %></span>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/thing/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>

<%= label f, :name %>
<%= text_input f, :name %>
<%= error_tag f, :name %>

<%= label f, :description %>
<%= textarea f, :description %>
<%= error_tag f, :description %>

<%= label f, :number %>
<%= number_input f, :number %>
<%= error_tag f, :number %>

<%= label f, :amount %>
<%= number_input f, :amount, step: "any" %>
<%= error_tag f, :amount %>

<%= label f, :flag %>
<%= checkbox f, :flag %>
<%= error_tag f, :flag %>

<%= label f, :event %>
<%= datetime_select f, :event %>
<%= error_tag f, :event %>

<div>
    <%= submit "Save" %>
</div>
<% end %>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/thing/index.html.eex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_live_path(@conn, :index) %>">Live View</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Things <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<h1>Listing Things</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Data</th>
            <th>Number</th>
            <th>Amount</th>
            <th>Flag</th>
            <th>Event</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= for thing <- @things do %>
        <tr>
            <td><%= thing.name %></td>
            <td><%= thing.description %></td>
            <td><%= inspect(thing.data) %></td>
            <td><%= thing.number %></td>
            <td><%= thing.amount %></td>
            <td><%= thing.flag %></td>
            <td><%= thing.event %></td>

            <td>
                <%= link "Show", to: Routes.thing_path(@conn, :show, thing) %>
                <%= link "Edit", to: Routes.thing_path(@conn, :edit, thing) %>
                <%= link "Delete", to: Routes.thing_path(@conn, :delete, thing), method: :delete, data: [confirm: "Are you sure?"] %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<span><%= link "New Thing", to: Routes.thing_path(@conn, :new) %></span>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/thing/new.html.eex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_live_path(@conn, :index) %>">Live View</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Things <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<h1>New Thing</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.thing_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.thing_path(@conn, :index) %></span>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/thing/show.html.eex
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Phoenix Live View Starter App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= Routes.page_live_path(@conn, :index) %>">Live View</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Things <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<h1>Show Thing</h1>

<ul>

    <li>
        <strong>Name:</strong>
        <%= @thing.name %>
    </li>

    <li>
        <strong>Description:</strong>
        <%= @thing.description %>
    </li>

    <li>
        <strong>Data:</strong>
        <%= inspect(@thing.data) %>
    </li>

    <li>
        <strong>Number:</strong>
        <%= @thing.number %>
    </li>

    <li>
        <strong>Amount:</strong>
        <%= @thing.amount %>
    </li>

    <li>
        <strong>Flag:</strong>
        <%= @thing.flag %>
    </li>

    <li>
        <strong>Event:</strong>
        <%= @thing.event %>
    </li>

</ul>

<span><%= link "Edit", to: Routes.thing_path(@conn, :edit, @thing) %></span>
<span><%= link "Back", to: Routes.thing_path(@conn, :index) %></span>

apps/phoenix_live_view_starter_app_web/lib/phoenix_live_view_starter_app_web/templates/thingamabobber_live/thingamabobber.html.leex
<h1 class="display-4">Thing <%= @thing %></h1>
<button type="button" class="btn btn-primary" phx-click="thingamabobber">Thingamabobber</button>